name: CIPR

on:
  pull_request: ~

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: dom, fileinfo, filter, gd, hash, intl, json, mbstring, mysqli, pcre, pdo_mysql, zlib
          coverage: none

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install the dependencies
        run: composer install --no-interaction --no-progress

      - name: Install PHPStan
        uses: ramsey/composer-install@v3

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src